---
- name: Check passwordless ssh
  hosts: localhost
  tasks:
  - name: Check for ulimit entry of Elastic search and storm
    command: grep -Fxq "elasticsearch - memlock unlimited\nstorm - nproc 257597" /etc/security/limits.conf
    register: out
    ignore_errors: yes
  - debug:
     msg: "Test Fail"
    when: out.failed == true
  - debug:
     msg: "test Pass"
    when: out.failed == false

  - name: Adjust limits to secure level
    command: grep -Fxq "* - nofile 32768" /etc/security/limits.conf
    register: out1
    ignore_errors: yes
  - debug:
     msg: "Test Fail"
    when: out1.failed == true
  - debug:
     msg: "test Pass"
    when: out1.failed == false

  - name: Adjust limits to secure level
    command: grep -Fxq "* - nproc 65536" /etc/security/limits.conf
    register: out2
    ignore_errors: yes
  - debug:
     msg: "Test Fail"
    when: out2.failed == true
  - debug:
     msg: "test Pass"
    when: out2.failed == false
